### ISSUE TITLE
Can you send a private link of most of your ... ¡¡RESPITORIES!!

### ISSUE THREAD

**Issue by ghost** [Windows81/GoAnimate-Character-Dump#3]

**Comment by Windows81** [comment]
I invited you to all the private repos that are associated with GoAnimate Wrapper.  Check your notifications.

**Comment by ghost** [comment]
theres no notafications, can you try again

**Comment by bsdf** [comment]
please invite

**Comment by Windows81** [comment]
Hit [this link](https://github.com/Windows81/GoAnimate-Wrapper/invitations).  I wouldn't recommend you tell anyone else about it for now.

**Comment by OrangeNickAnimate** [comment]
Invite me to all of your repos plz
