### ISSUE TITLE
Can I upload characters to the dump? 

### ISSUE THREAD

**Issue by OrangeNickAnimate** [Windows81/GoAnimate-Character-Dump#5]

**Comment by OrangeNickAnimate** [comment]
I just want to upload charecters

**Comment by Windows81** [comment]
Hi.  As this is a historical archive for characters created on Vyond's servers, I wouldn't recommend doing that; the characters are stored in a specialised format.  Additionally, I'm probably gonna shut GoAnimate Wrapper down anyway in a final effort to comply with Vyond's takedown request from a few months earlier.
